<a href="https://colab.research.google.com/github/Omdena-Bhutan/numpy-panda-ngawang-zangphel/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Import the libraries
import numpy as np

# Numpy Array

## Quiz on 1D Numpy Array

In [15]:
# Write your code below and press Shift+Enter to execute
u = np.array([1, 0])
v = np.array([0, 1])
print(u -v)


[ 1 -1]


Multiply the numpy array z with -2:

In [16]:
z = np.array([2, 4])
print(z * (-2))

[-4 -8]


Consider the list <code>\[1, 2, 3, 4, 5]</code> and <code>\[1, 0, 1, 0, 1]</code>. Cast both lists to a numpy array then multiply them together:


In [17]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 0, 1, 0, 1])
print(x * y)

[1 0 3 0 5]


# 2D Numpy

<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array.


In [9]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
npArray = np.array(a)
print(npArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Calculate the numpy array size.


In [10]:
# Write your code below and press Shift+Enter to execute
print(npArray.size)

12


Access the element on the first row and first and second columns.


In [11]:
# Write your code below and press Shift+Enter to execute
print(npArray[0][0:2])

[1 2]


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [12]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
matrixProd = np.dot(npArray, B)
print(matrixProd)

[[ 1  4]
 [ 5 12]
 [ 9 20]]
